from datetime import datetime
import logging
import os

import resend
from logging_config import setup_logging

# Setup logging
setup_logging()
logger = logging.getLogger(__name__)

resend.api_key = os.getenv('RESEND_API_KEY')

class CompanyEmailSender:
    def __init__(self, email_to: str, subject: str, report_html: str, company_id: str):
        self.email_to = email_to
        self.subject = subject
        self.report_html = report_html
        self.company_id = company_id
        
    def send_email(self) -> bool:
        logger.info(
            f"Sending email to {self.email_to}"
            f"with subject {self.subject}"
            f"and report html {self.report_html}"
        )
        html = f"""
<html>  
<body>
QuickBooks Report for {self.company_id}

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{self.report_html}

---
This report was automatically generated by the QBO Report Scheduler.
</body>
</html>
        """

        response = resend.Emails.send({
            "from": "QBO Reports <onboarding@resend.dev>",
            "to": [self.email_to],
            "subject": self.subject,
            "html": html
        })
        return response is not None